### ISSUE TITLE
Duplicated backslash char, wrong math characters

### ISSUE THREAD

**Issue by aminophen** [aminophen/dviasm#12]
It seems that the upstream is now archived (https://github.com/khaledhosny/dviasm), so I don't know where to report this.  This is just a note. (@khaledhosny)

``` tex
\documentclass{article}
\begin{document}

\verb+\usepackage{amsmath}+
$-1$

\begin{itemize}
\item First
\item Second
\end{itemize}

\end{document}
```

### Original DVI

```
$ latex test.tex
$ dvipdfmx test.dvi
```

<img width="247" alt="20200830-dviasm-0" src="https://user-images.githubusercontent.com/9957466/91656786-683e7700-eaf6-11ea-87ee-51399b683b44.png">

### After processing with DVIasm

```
$ dviasm test.dvi >test-out.txt
$ dviasm -o test-out.dvi test-out.txt
$ dvipdfmx test-out.dvi
```

<img width="278" alt="20200830-dviasm-1" src="https://user-images.githubusercontent.com/9957466/91656787-6b396780-eaf6-11ea-99c1-3480226a3246.png">

**Comment by aminophen** [comment]
@khaledhosny Recieved - Thanks! I will update there.

**Comment by reutenauer** [comment]
I think you should also make the transfer official from [CTAN](https://www.ctan.org/pkg/dviasm)’s point of view, i. e., let them know that Hironobu is now the maintainer of `dviasm`.

**Comment by khaledhosny** [comment]
As it happened with Libertinus, when @aminophen upload a new version CTAN will confirm with me.

**Comment by aminophen** [comment]
The original issue (escape sequence, math characters) are now fixed.
