### ISSUE TITLE
Support request for XDV_ID other than 6

### ISSUE THREAD

**Issue by aminophen** [aminophen/dviasm#2]
Recent version (TeX Live 2017) of XeTeX produces XDV file with id = 7, however, dviasm accepts only id = 6. According to xetex.web, the id = {4,5,6,7} is possible in the history of XeTeX, so it would be nice if all of these id's are accepted.

**Comment by aminophen** [comment]
Thank you, it seems working (the new opcode is not well tested, sorry). I hope the new version will be available from CTAN, as the current TeX Live version assembles text into corrupted XDV with id = 2.

**Comment by khaledhosny** [comment]
I just uploaded the new version to CTAN.

**Comment by aminophen** [comment]
Thanks!
