### ISSUE TITLE
dviasm does not work with characters beyond 0x10000

### ISSUE THREAD

**Issue by iajoiner** [aminophen/dviasm#6]
I used `unicode-math` to convert the characters on the paper to Unicode. After that dviasm ceased to work.

Traceback:
Traceback (most recent call last):
  File "../dviasm/dviasm.py", line 1214, in <module>
    else:              aDVI.DumpToFile(sys.stdout, tabsize=options.tabsize, encoding=options.encoding)
  File "../dviasm/dviasm.py", line 936, in DumpToFile
    fp.write("set: %s\n" % PutStr(cmd[1]))
  File "../dviasm/dviasm.py", line 230, in PutStrUTF8
    else:               s += unichr(o).encode('utf8')
ValueError: unichr() arg not in range(0x10000) (narrow Python build)

Many mathematical alphanumerical symbols are outside this range. Maybe if you are willing to explain how this works I can help you fix it.

**Comment by khaledhosny** [comment]
That is a Python 2 limitation. Some Python 2 builds are “narrow builds” (as the error indicates) where only characters in the BMP are supported. You need to either use a wide Python build, or we do a workaround like [this](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/misc/py23.py#L32-L65) in dviasm.

**Comment by iajoiner** [comment]
Thanks! That works!
